server:
  port: 9001


spring:
  application:
    name: nacos-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.11:8860
      #server-addr: localhost:8848

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.simpler.springcloudalibaba.entities    # 所有Entity别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: "*"
